services:
  - type: web
    name: zap-remover-api-key
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: zapremoverbg369
        value: 123456
